# Generated by Django 5.2.4 on 2025-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythical', 'Mythical'), ('ultrabeast', 'UltraBeast')], default='common', max_length=20),
        ),
    ]
